all:
	g++ -std=c++17 Principal.cpp -o vision.bin -lstdc++fs -I/usr/local/include/opencv4/ -L/usr/local/lib/ -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio
run:
	./vision.bin

saludo:
	echo "Hola desde C++!!!"

