all:
	g++ Principal.cpp --std=c++17 -I/home/lubuntu/Descargas/OpenCV-android-sdk/sdk/native/jni/include/ -L/home/lubuntu/Documentos/OpenCV-android-sdk/sdk/native/libs/ -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_objdetect -lopencv_videoio -o vision.bin

saludo:
	echo "Hola C++"

run:
	./vision.bin
